project:
  type: website
  output-dir: _output
  preview:
    port: 4269
    browser: false

format:
  revealjs:
    theme: night
    slide-number: true
    smaller: true
    embed-resources: true

lightbox: true
bibliography: ../../references/MSc_Thesis-Bibliography.bib
csl: apa.csl
author:
  - name: Alexandre Bry
    email: abry.pro@proton.me

css: styles.css
